version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    commit-message:
      prefix: "ci"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    target-branch: develop
    commit-message:
      prefix: "build"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
