/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGamesRouteImport } from './routes/_app/games'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTimelineIndexRouteImport } from './routes/_app/timeline.index'
import { Route as AppTimelineStreamIdRouteImport } from './routes/_app/timeline.$streamId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineIndexRoute = AppTimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineStreamIdRoute = AppTimelineStreamIdRouteImport.update({
  id: '/timeline/$streamId',
  path: '/timeline/$streamId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/games': typeof AppGamesRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/users': typeof AppUsersRoute
  '/timeline/$streamId': typeof AppTimelineStreamIdRoute
  '/timeline/': typeof AppTimelineIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/games': typeof AppGamesRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/timeline/$streamId': typeof AppTimelineStreamIdRoute
  '/timeline': typeof AppTimelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/games': typeof AppGamesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/timeline/$streamId': typeof AppTimelineStreamIdRoute
  '/_app/timeline/': typeof AppTimelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/setup'
    | '/games'
    | '/history'
    | '/settings'
    | '/subscriptions'
    | '/users'
    | '/timeline/$streamId'
    | '/timeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/setup'
    | '/games'
    | '/history'
    | '/settings'
    | '/subscriptions'
    | '/users'
    | '/'
    | '/timeline/$streamId'
    | '/timeline'
  id:
    | '__root__'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/setup'
    | '/_app/games'
    | '/_app/history'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/users'
    | '/_app/'
    | '/_app/timeline/$streamId'
    | '/_app/timeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline/': {
      id: '/_app/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof AppTimelineIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline/$streamId': {
      id: '/_app/timeline/$streamId'
      path: '/timeline/$streamId'
      fullPath: '/timeline/$streamId'
      preLoaderRoute: typeof AppTimelineStreamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGamesRoute: typeof AppGamesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTimelineStreamIdRoute: typeof AppTimelineStreamIdRoute
  AppTimelineIndexRoute: typeof AppTimelineIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGamesRoute: AppGamesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppTimelineStreamIdRoute: AppTimelineStreamIdRoute,
  AppTimelineIndexRoute: AppTimelineIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
